name: Deploy to Google VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VM via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_DEPLOY_KEY }}
          port: 22
          source: "."
          target: "/home/<user>/LineOA-English-Mania"

      - name: SSH and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/<user>/LineOA-English-Mania
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f "uvicorn" || true
            nohup uvicorn app.main:app --host 0.0.0.0 --port 8080 &